<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel='stylesheet' href='https://unpkg.com/emoji.css/dist/emoji.min.css'>
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <!-- Bootstrap JS-->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- My CSS-->
  <link rel="stylesheet" href="css/styles.css">
  <link rel="stylesheet" href="css/sidebar.css">
  <link rel="stylesheet" href="css/product-filter.css">
  <link rel="stylesheet" href="css/product-card.css">


  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com"> 
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
  <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
</head>
<style>
  body {
    background-image: url("images/space-temp.png");
    background-size: cover;
    background-attachment: fixed;
  }
  .custom-toggler .navbar-toggler-icon {
    background-image: url(svg/good_enough_hamburger_menu.svg);
  }
</style>


<?php

session_start();
$user_id = $_SESSION['user_id'];
if($user_id != ""){
        $_SESSION['user_id'] = $user_id;
}


echo '<body>';
echo '';
echo '<nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: black;">';
echo '<button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<a class="navbar-brand space-font" href="index.php" style="color: rgb(173, 222, 255);">soundspace.com</a>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbarTogglerDemo03">';
echo '<ul class="navbar-nav mr-auto mt-2 mt-lg-0">';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="vinyls.php" style="color: rgb(173, 222, 255);">Vinyls</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="players.html" style="color: rgb(173, 222, 255);">Record Players</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="headphones.html" style="color: rgb(173, 222, 255);">Headphones</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="login.php" style="color: rgb(173, 222, 255);">Log in <img src="svg/user.svg"></a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="cart.php" style="color: rgb(173, 222, 255);">Cart <img src="svg/shopping-cart.svg"></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<!-- Page content -->';
echo '';
echo '<div class="d-flex justify-content-center">';
echo '<h1 class="space-font" style="font-size: 2em; background-color: black; border: black 2px solid;">Browse Our Extensive Vinyl Collection</h1>';
echo '</div>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '';
//echo '<div class="d-flex justify-content-center">';
echo '';
//echo '<form class="form-inline">';
//echo '<div class="form-group mx-sm-3 mb-2 my-form-settings center-custom">';
//echo '<label for="inputPassword2" class="sr-only my-form-settings">Search</label>';
//echo '<input type="text" class="form-control my-form-settings" id="search" placeholder="Search" onkeyup="myfunc()">';
//echo '</div>';
//echo '</form>';
//echo '</div>';
echo '';
echo '';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<div class="container" id="card-list">';
echo '<div class="d-flex justify-content-center">';
echo '<div class="card-deck">';
echo '';
echo '<!-- begin first line -->';
echo '';
echo '<div class="card country_folk">';
echo '<a href="product_page.php?vinyl_id=1">';
echo '<img src="images/Johnny_Cash_At_Folsom_Prison.jpg" class="card-img-top" alt="Album art for At Folsom Prison by Johnny Cash.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">At Folsom Prison - Johnny Cash</h5>';
echo '<p class="card-text">Johnny Cash at Folsom Prison is the first live album by American...</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '';
echo '';
echo '<div class="card reggaeton_latin">';
echo '<a href="product_page.php?vinyl_id=2">';
echo '<img src="images/bad_bunny-x100pre.jpg" class="card-img-top" alt="Album art for X 100pre by Bad Bunny.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">X 100pre - Bad Bunny</h5>';
echo '<p class="card-text">X 100pre (an abbreviation of "Por siempre" in Spanish, meaning "Forever"...</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '';
echo '';
echo '<div class="card rap_hiphop">';
echo '<a href="product_page.php?vinyl_id=3">';
echo '<img src="images/Gunna_-_Wunna.png" class="card-img-top" alt="Album art for Wunna by Gunna.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Wunna - Gunna</h5>';
echo '<p class="card-text">Wunna (stylized in all caps) is the second studio album by American rapper Gunna...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card Alternative">';
echo '<a href="product_page.php?vinyl_id=4">';
echo '<img src="images/Black_Dresses_-_Peaceful_as_Hell.png" class="card-img-top" alt="Album art for Peaceful as Hell by Black Dresses.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Peaceful as Hell - Black Dresses</h5>';
echo '<p class="card-text">Peaceful as Hell is an electronic album with elements of industrial, noise, glitch...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card Ambient">';
echo '<a href="product_page.php?vinyl_id=5">';
echo '<img src="images/drukqs-aphex_twin.png" class="card-img-top" alt="Album art for Drukqs by Aphex Twin.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Drukqs - Aphex Twin</h5>';
echo '<p class="card-text">Drukqs (stylised as drukQs) is the fifth studio album by Aphex Twin, the...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end first line -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin second line -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=6">';
echo '<img src="images/YHLQMDLG_Bad Bunny.jpg" class="card-img-top" alt="Album art for YHLQMDLG by Bad Bunny.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">YHLQMDLG - Bad Bunny</h5>';
echo '<p class="card-text">YHLQMDLG is a reggaeton and Latin trap album, that incorporates...</p>';
echo '</div>';
echo '</div>';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=7">';
echo '<img src="images/Kanyewest_collegedropout.jpg" class="card-img-top" alt="Album art for College Dropout by Kanye West.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">The College Dropout - Kanye West</h5>';
echo '<p class="card-text">The College Dropout diverged from the then-dominant...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=8">';
echo '<img src="images/ye.jpg" class="card-img-top" alt="Album art for Ye by Kanye West.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Ye - Kanye West</h5>';
echo '<p class="card-text">Ye is the eighth studio album by American rapper Kanye West. It was released on June 1, 2018...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=9">';
echo '<img src="images/Die_Lit_by_Playboi_Carti.jpg" class="card-img-top" alt="Album art for Die Lit by Playboy Carti.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Die Lit - Playboi Carti</h5>';
echo '<p class="card-text">Die Lit is the debut studio album by American rapper Playboi Carti. It...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=10">';
echo '<img src="images/Be_the_Cowboy.jpg" class="card-img-top" alt="Album art for Be the Cowboy by Mitski.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Be the Cowboy - Mitski</h5>';
echo '<p class="card-text">Be the Cowboy is the fifth studio album by Japanese-American indie rock musician...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end second line -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin third line -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=11">';
echo '<img src="images/CollidewiththeSkycover.jpg" class="card-img-top" alt="Album art for Collide with the Sky by Pierce the Veil.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Collide with the Sky - Pierce the Veil</h5>';
echo '<p class="card-text">Collide with the Sky is the third studio album by American...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=12">';
echo '<img src="images/Danger_Days-album-2010.jpg" class="card-img-top" alt="Album art for Danger Days by My Chemical Romance.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Danger Days - My Chemical Romance</h5>';
echo '<p class="card-text">Danger Days: The True Lives of the Fabulous Killjoys...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=13">';
echo '<img src="images/Mitski-Laurel-Hell.jpg" class="card-img-top" alt="Album art for Laurel Hell by Mitski.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Laurel Hell - Mitski</h5>';
echo '<p class="card-text">Laurel Hell is the sixth studio album by Japanese-American singer-songwriter...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=14">';
echo '<img src="images/limbo_amine.jpg" class="card-img-top" alt="Album art for Limbo by Aminé.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Limbo - Aminé</h5>';
echo '<p class="card-text">Limbo is the second studio album by American rapper Aminé. It was released on August...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=15">';
echo '<img src="images/public_void_p_scott.jpg" class="card-img-top" alt="Album art for Public Void by Penelope Scott.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Public Void - Penelope Scott</h5>';
echo '<p class="card-text">Scott’s second full-length album is an exploration into growing up to...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end third row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin fourth row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=16">';
echo '<img src="images/wasteland_baby.jpg" class="card-img-top" alt="Album art for Wasteland Baby by Hozier.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Wasteland Baby - Hozier</h5>';
echo '<p class="card-text">Wasteland, Baby! is just under an hour long, containing fourteen...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=17">';
echo '<img src="images/the_frights_you_are_going.jpg" class="card-img-top" alt="Album art for You Are Going to Hate This by The Frights.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">You Are Going To Hate This - The Frights</h5>';
echo '<p class="card-text">A hormonally charged garage-surf-punk mess of driving...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=18">';
echo '<img src="images/Igor_-_Tyler,_the_Creator.jpg" class="card-img-top" alt="Album art for Igor by Tyler, the Creator.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Igor - Tyler, the Creator</h5>';
echo '<p class="card-text">Igor is the fifth studio album by American rapper and producer Tyler, the Creator...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=19">';
echo '<img src="images/Kids_See_Ghosts_Cover.png" class="card-img-top" alt="Album art for Kids See Ghosts by Kanye West & Kid Cudi.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Kids See Ghosts - Kanye West & Kid Cudi</h5>';
echo '<p class="card-text">According to Jordan Bassett of NME, Kids See Ghosts shows...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=20">';
echo '<img src="images/The Slow Rush_Tame Impala.jpg" class="card-img-top" alt="Album art for The Slow Rush by Tame Impala.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">The Slow Rush - Tame Impala</h5>';
echo '<p class="card-text">The Slow Rush was called "an extraordinarily detailed opus" that...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end fourth row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin fifth row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=21">';
echo '<img src="images/silk_sonic.jpeg" class="card-img-top" alt="Album art for An Evening with Silk Sonic by Bruno Mars & Anderson .Paak.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">An Evening with Silk Sonic - Bruno Mars & Anderson .Paak</h5>';
echo '<p class="card-text">An Evening with Silk Sonic has been...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=22">';
echo '<img src="images/Metallica_-_Master_of_Puppets_cover.jpg" class="card-img-top" alt="Album art for Master of Puppets by Metallica.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Master of Puppets - Metallica</h5>';
echo '<p class="card-text">Master of Puppets features dynamic music and thick...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=23">';
echo '<img src="images/jackboys_travis.jpg" class="card-img-top" alt="Album art for JackBoys by JackBoys & Travis Scott.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">JackBoys - Jackboys & Travis Scott</h5>';
echo '<p class="card-text">JackBoys (stylized as JACKBOYS) is a compilation album...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=24">';
echo '<img src="images/Ariana_Grande_-_Positions.png" class="card-img-top" alt="Album art for Positions by Ariana Grande.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Positions - Ariana Grande</h5>';
echo '<p class="card-text">Musically, Positions is an R&B and pop record with trap inflections...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=25">';
echo '<img src="images/juice.jpg" class="card-img-top" alt="Album art for Goodbye & Good Riddance by Juice WRLD.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Goodbye & Good Riddance - Juice WRLD</h5>';
echo '<p class="card-text">Musically, Positions is an R&B and pop record with trap...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end fifth row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin sixth row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=26">';
echo '<img src="images/calle_13.jpeg" class="card-img-top" alt="Album art for Mala Suerte con el 13 by Calle 13.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Mala Suerte con el 13 - Calle 13</h5>';
echo '<p class="card-text">Description unavailable.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=27">';
echo '<img src="images/EMINEM-The-Slim-Shady-LP-Vinyl-2xLP-black.jpg" class="card-img-top" alt="Album art for The Slim Shady  LP by Eminem.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">The Slim Shady LP - Eminem</h5>';
echo '<p class="card-text">The Slim Shady LP is the second studio album by American rapper Eminem...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=28">';
echo '<img src="images/Tame_Impala_-_Currents.png" class="card-img-top" alt="Album art for Currents by Tame Impala.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Currents - Tame Impala</h5>';
echo '<p class="card-text">Currents is the third studio album by Australian musical project...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=29">';
echo '<img src="images/Blink-182-Take-Off-Your-Pants-And-Jacket-album-cover-02.jpg" class="card-img-top" alt="Album art for Take Off Your Pants and Jacket by Blink-182.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Take Off Your Pants and Jacket - Blink-182</h5>';
echo '<p class="card-text">Take Off Your Pants and Jacket is the fourth studio album...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=30">';
echo '<img src="images/Green_Day_-_American_Idiot_album_cover.png" class="card-img-top" alt="Album art for American Idiot by Green Day.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">American Idiot - Green Day</h5>';
echo '<p class="card-text">American Idiot is the seventh studio album by American rock band...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end sixth row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin seventh row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=31">';
echo '<img src="images/watch_the_throne.jpg" class="card-img-top" alt="Album art for Watch the Throne by Kanye West & Jay Z.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Watch The Throne - Kanye West & Jay Z</h5>';
echo '<p class="card-text">Watch the Throne is a collaborative studio album by American...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=32">';
echo '<img src="images/Playboi_Carti_-_mixtape.jpg" class="card-img-top" alt="Album art for Playboi Carti by Playboi Carti.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Playboi Carti - Playboi Carti</h5>';
echo '<p class="card-text">Playboi Carti (commonly referred to as Self Titled) is the eponymous debut...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=33">';
echo '<img src="images/In_the_aeroplane_over_the_sea_album_cover_copy.jpg" class="card-img-top" alt="Album art for In the Aeroplane Over the Sea by Neutral Milk Hotel.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">In The Aeroplane Over The Sea - Neutral Milk Hotel</h5>';
echo '<p class="card-text">In the Aeroplane Over the Sea is the...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=34">';
echo '<img src="images/spiderman_of_the_rings.jpg" class="card-img-top" alt="Album art for Spiderman of the Rings by Dan Deacon.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Spiderman of the Rings - Dan Deacon</h5>';
echo '<p class="card-text">Spiderman of the Rings is the first studio album by the...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=35">';
echo '<img src="images/5150.jpeg" class="card-img-top" alt="Album art for 5150 by Van Halen.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">5150 - Van Halen</h5>';
echo '<p class="card-text">5150 (pronounced "fifty-one-fifty") is the seventh studio album by American rock band...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end seventh row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin eighth row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=36">';
echo '<img src="images/Tay-k.jpeg" class="card-img-top" alt="Album art for #SantanaWorld (+) by Tay-K.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">#SantanaWorld (+) - Tay-K</h5>';
echo '<p class="card-text">Santana World (stylized as #SantanaWorld) is the only mixtape by...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=37">';
echo '<img src="images/Radioheadokcomputer.png" class="card-img-top" alt="Album art for OK Computer by Radiohead.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">OK Computer - Radiohead</h5>';
echo '<p class="card-text">OK Computer is the third studio album by the English rock band Radiohead...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=38">';
echo '<img src="images/1000 gecs and the tree of clues_100 gecs.jpg" class="card-img-top" alt="Album art for 1000 Gecs and the Tree of Clues by 100 gecs.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">1000 Gecs and The Tree of Clues - 100 gecs</h5>';
echo '<p class="card-text">1000 Gecs and the Tree of Clues (stylized as 1000 gecs and...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=39">';
echo '<img src="images/Anuel_AA_-_Real_Hasta_la_Muerte.png" class="card-img-top" alt="Album art for Real Hasta la Muerte by Anuel AA.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Real Hasta la Muerte - Anuel AA</h5>';
echo '<p class="card-text">Real Hasta la Muerte is the debut studio album by Puerto...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=40">';
echo '<img src="images/kendrick_tpabf.jpg" class="card-img-top" alt="Album art for To Pimp a Butterfly by Kendrick Lamar.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">To Pimp A Butterfly - Kendrick Lamar</h5>';
echo '<p class="card-text">Primarily a hip hop album, To Pimp a Butterfly...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end eighth row -->';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- begin ninth row -->';
echo '<div class="d-flex justify-content-center mt-5">';
echo '<div class="card-deck">';
echo '<div class="card">';
echo '<a href="product_page.php?vinyl_id=41">';
echo '<img src="images/good_kid.jpeg" class="card-img-top" alt="Album art for good kid, m.A.A.d city by Kendrick Lamar.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">good kid, m.A.A.d city - Kendrick Lamar</h5>';
echo '<p class="card-text">good Kid, M.A.A.D City has a low-key, downbeat...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=42">';
echo '<img src="images/TheMelodicBlueCover.jpeg" class="card-img-top" alt="Album art for The Melodic Blue by Baby Keem.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">The Melodic Blue - Baby Keem</h5>';
echo '<p class="card-text">The Melodic Blue is the debut studio album by American rapper...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=43">';
echo '<img src="images/how_to_leave.jpg" class="card-img-top" alt="Album art for How to Leave Town by Car Seat Headrest.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">How To Leave Town - Car Seat Headrest</h5>';
echo '<p class="card-text">Originally released on Will Toledos bandcamp in...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=44">';
echo '<img src="images/pixies.jpg" class="card-img-top" alt="Album art for Surfer Rosa by Pixies.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Surfer Rosa - Pixies</h5>';
echo '<p class="card-text">Surfer Rosa is the debut studio album by the American alternative...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="card ">';
echo '<a href="product_page.php?vinyl_id=45">';
echo '<img src="images/Beach_House_-_Bloom.png" class="card-img-top" alt="Album art for Bloom by Beach House.">';
echo '</a>';
echo '<div class="card-body">';
echo '<h5 class="card-title">Bloom - Beach House</h5>';
echo '<p class="card-text">Bloom is the fourth studio album by American dream pop duo Beach...</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- end ninth row -->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '<br>';
echo '<br>';
echo '';
echo '</html>';
echo '';
echo '';
echo '<script>';
echo '';
echo 'function myfunc(){';
echo "const zupu = document.getElementById('search').value.toUpperCase();";
echo "const wopa = document.getElementById('card-list');";
echo '// aqui por fin las cartas';
echo "const cards = wopa.getElementsByClassName('card');";
echo 'console.log(cards);';
echo '';
echo 'for(let i = 0; i < cards.length; i++){';
echo "let title = cards[i].querySelector('.card-body h5.card-title');";
echo 'console.log(title);';
echo '';
echo 'if(title.innerText.toUpperCase().indexOf(zupu) > -1) {';
echo 'cards[i].style.display = "";';
echo '}else{';
echo 'cards[i].style.display = "none";';
echo '}';
echo '}';
echo '';
echo '}';
echo '</script>';
